// auth
// eslint-disable-next-line import/prefer-default-export
export const userConstants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  API_CALL_ERROR: 'API_CALL_ERROR',

  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  FORGET_PASSWORD_REQUEST: 'FORGET_PASSWORD_REQUEST',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAIL: 'FORGET_PASSWORD_FAIL',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
};

export const courseConstants = {
  FETCH_COURSES_START: 'FETCH_COURSES_START',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAIL: 'FETCH_COURSES_FAIL',

  ADD_COURSE_START: 'ADD_COURSE_START',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAIL: 'ADD_COURSE_FAIL',

  RENAME_COURSE_START: 'RENAME_COURSE_START',
  RENAME_COURSE_SUCCESS: 'RENAME_COURSE_SUCCESS',
  RENAME_COURSE_FAIL: 'RENAME_COURSE_FAIL',

  DELETE_COURSE_START: 'DELETE_COURSE_START',
  DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
  DELETE_COURSE_FAIL: 'DELETE_COURSE_FAIL',

  FETCH_CLASSES_START: 'FETCH_CLASSES_START',
  FETCH_CLASSES_SUCCESS: 'FETCH_CLASSES_SUCCESS',
  FETCH_CLASSES_FAIL: 'FETCH_CLASSES_FAIL',

  ADD_CLASS_START: 'ADD_CLASS_START',
  ADD_CLASS_SUCCESS: 'ADD_CLASS_SUCCESS',
  ADD_CLASS_FAIL: 'ADD_CLASS_FAIL',

  RENAME_CLASS_START: 'RENAME_CLASS_START',
  RENAME_CLASS_SUCCESS: 'RENAME_CLASS_SUCCESS',
  RENAME_CLASS_FAIL: 'RENAME_CLASS_FAIL',

  DELETE_CLASS_START: 'DELETE_CLASS_START',
  DELETE_CLASS_SUCCESS: 'DELETE_CLASS_SUCCESS',
  DELETE_CLASS_FAIL: 'DELETE_CLASS_FAIL',

  FETCH_MEMBERS_START: 'FETCH_MEMBERS_START',
  FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS',
  FETCH_MEMBERS_FAIL: 'FETCH_MEMBERS_FAIL',

  EDIT_MEMBERS_START: 'EDIT_MEMBERS_START',
  EDIT_MEMBERS_SUCCESS: 'EDIT_MEMBERS_SUCCESS',
  EDIT_MEMBERS_FAIL: 'EDIT_MEMBERS_FAIL',
};
