// eslint-disable-next-line import/prefer-default-export
export const commonConstants = {
  GET_INSTITUTE_START: 'GET_INSTITUTE_START',
  GET_INSTITUTE_SUCCESS: 'GET_INSTITUTE_SUCCESS',
  GET_INSTITUTE_FAIL: 'GET_INSTITUTE_FAIL',

  FETCH_CLASS_MEMBERS_START: 'FETCH_CLASS_MEMBERS_START',
  FETCH_CLASS_MEMBERS_SUCCESS: 'FETCH_CLASS_MEMBERS_SUCCESS',
  FETCH_CLASS_MEMBERS_FAIL: 'FETCH_CLASS_MEMBERS_FAIL',

  FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_START: 'FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_START',
  FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_SUCCESS: 'FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_SUCCESS',
  FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_FAIL: 'FETCH_CLASS_MEMBER_WITH_ACCOUNT_REFERRAL_FAIL',

  REPLACE_CLASS_MEMBERS_START: 'REPLACE_CLASS_MEMBERS_START',
  REPLACE_CLASS_MEMBERS_SUCCESS: 'REPLACE_CLASS_MEMBERS_SUCCESS',
  REPLACE_CLASS_MEMBERS_FAIL: 'REPLACE_CLASS_MEMBERS_FAIL',

  BROWSE_SUBMISSION_LANG_START: 'BROWSE_SUBMISSION_LANG_START',
  BROWSE_SUBMISSION_LANG_SUCCESS: 'BROWSE_SUBMISSION_LANG_SUCCESS',
  BROWSE_SUBMISSION_LANG_FAIL: 'BROWSE_SUBMISSION_LANG_FAIL',

  FETCH_COURSE_START: 'FETCH_COURSE_START',
  FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
  FETCH_COURSE_FAIL: 'FETCH_COURSE_FAIL',

  FETCH_ALL_CLASSES_START: 'FETCH_ALL_CLASSES_START',
  FETCH_ALL_CLASSES_SUCCESS: 'FETCH_ALL_CLASSES_SUCCESS',
  FETCH_ALL_CLASSES_FAIL: 'FETCH_ALL_CLASSES_FAIL',

  FETCH_CLASS_START: 'FETCH_CLASS_START',
  FETCH_CLASS_SUCCESS: 'FETCH_CLASS_SUCCESS',
  FETCH_CLASS_FAIL: 'FETCH_CLASS_FAIL',

  READ_CHALLENGE_START: 'READ_CHALLENGE_START',
  READ_CHALLENGE_SUCCESS: 'READ_CHALLENGE_SUCCESS',
  READ_CHALLENGE_FAIL: 'READ_CHALLENGE_FAIL',

  FETCH_ACCOUNT_START: 'FETCH_ACCOUNT_START',
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  FETCH_ACCOUNT_FAIL: 'FETCH_ACCOUNT_FAIL',

  DOWNLOAD_FILE_START: 'DOWNLOAD_FILE_START',
  DOWNLOAD_FILE_SUCCESS: 'DOWNLOAD_FILE_SUCCESS',
  DOWNLOAD_FILE_FAIL: 'DOWNLOAD_FILE_FAIL',

  FETCH_DOWNLOAD_FILE_URL_START: 'FETCH_DOWNLOAD_FILE_URL_START',
  FETCH_DOWNLOAD_FILE_URL_SUCCESS: 'FETCH_DOWNLOAD_FILE_URL_SUCCESS',
  FETCH_DOWNLOAD_FILE_URL_FAIL: 'FETCH_DOWNLOAD_FILE_URL_FAIL',

  FETCH_ALL_CHALLENGES_PROBLEMS_START: 'FETCH_ALL_CHALLENGES_PROBLEMS_START',
  FETCH_ALL_CHALLENGES_PROBLEMS_SUCCESS: 'FETCH_ALL_CHALLENGES_PROBLEMS_SUCCESS',
  FETCH_ALL_CHALLENGES_PROBLEMS_FAIL: 'FETCH_ALL_CHALLENGES_PROBLEMS_FAIL',

  FETCH_PROBLEMS_START: 'FETCH_PROBLEMS_START',
  FETCH_PROBLEMS_SUCCESS: 'FETCH_PROBLEMS_SUCCESS',
  FETCH_PROBLEMS_FAIL: 'FETCH_PROBLEMS_FAIL',

  GET_ACCOUNT_BATCH_START: 'GET_ACCOUNT_BATCH_START',
  GET_ACCOUNT_BATCH_SUCCESS: 'GET_ACCOUNT_BATCH_SUCCESS',
  GET_ACCOUNT_BATCH_FAIL: 'GET_ACCOUNT_BATCH_FAIL',

  GET_ACCOUNT_BATCH_BY_REFERRAL_START: 'GET_ACCOUNT_BATCH_BY_REFERRAL_START',
  GET_ACCOUNT_BATCH_BY_REFERRAL_SUCCESS: 'GET_ACCOUNT_BATCH_BY_REFERRAL_SUCCESS',
  GET_ACCOUNT_BATCH_BY_REFERRAL_FAIL: 'GET_ACCOUNT_BATCH_BY_REFERRAL_FAIL',
};
