// eslint-disable-next-line import/prefer-default-export
export const commonConstants = {
  GET_INSTITUTE_START: 'GET_INSTITUTE_START',
  GET_INSTITUTE_SUCCESS: 'GET_INSTITUTE_SUCCESS',
  GET_INSTITUTE_FAIL: 'GET_INSTITUTE_FAIL',

  FETCH_CLASS_MEMBERS_REQUEST: 'FETCH_CLASS_MEMBERS_REQUEST',
  FETCH_CLASS_MEMBERS_SUCCESS: 'FETCH_CLASS_MEMBERS_SUCCESS',
  FETCH_CLASS_MEMBERS_FAIL: 'FETCH_CLASS_MEMBERS_FAIL',

  EDIT_CLASS_MEMBER_REQUEST: 'EDIT_CLASS_MEMBER_REQUEST',
  EDIT_CLASS_MEMBER_SUCCESS: 'EDIT_CLASS_MEMBER_SUCCESS',
  EDIT_CLASS_MEMBER_FAIL: 'EDIT_CLASS_MEMBER_FAIL',

  DELETE_CLASS_MEMBER_REQUEST: 'DELETE_CLASS_MEMBER_REQUEST',
  DELETE_CLASS_MEMBER_SUCCESS: 'DELETE_CLASS_MEMBER_SUCCESS',
  DELETE_CLASS_MEMBER_FAIL: 'DELETE_CLASS_MEMBER_FAIL',

  FETCH_CLASS_REQUEST: 'FETCH_CLASS_REQUEST',
  FETCH_CLASS_SUCCESS: 'FETCH_CLASS_SUCCESS',
  FETCH_CLASS_FAIL: 'FETCH_CLASS_FAIL',
};
