export const viewConstants = {
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL',

  BROWSE_CLASS_MEMBER_START: 'BROWSE_CLASS_MEMBER_START',
  BROWSE_CLASS_MEMBER_SUCCESS: 'BROWSE_CLASS_MEMBER_SUCCESS',
  BROWSE_CLASS_MEMBER_FAIL: 'BROWSE_CLASS_MEMBER_FAIL',

  BROWSE_SUBMISSION_UNDER_CLASS_START: 'BROWSE_SUBMISSION_UNDER_CLASS_START',
  BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS: 'BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS',
  BROWSE_SUBMISSION_UNDER_CLASS_FAIL: 'BROWSE_SUBMISSION_UNDER_CLASS_FAIL',

  BROWSE_MYSUBMISSION_START: 'BROWSE_MYSUBMISSION_START',
  BROWSE_MYSUBMISSION_SUCCESS: 'BROWSE_MYSUBMISSION_SUCCESS',
  BROWSE_MYSUBMISSION_FAIL: 'BROWSE_MYSUBMISSION_FAIL',

  BROWSE_ACCESS_LOG_START: 'BROWSE_ACCESS_LOG_START',
  BROWSE_ACCESS_LOG_SUCCESS: 'BROWSE_ACCESS_LOG_SUCCESS',
  BROWSE_ACCESS_LOG_FAIL: 'BROWSE_ACCESS_LOG_FAIL',
};

export const courseConstants = {};

export const peerReviewConstants = {
  READ_PEER_REVIEW_START: 'READ_PEER_REVIEW_START',
  READ_PEER_REVIEW_SUCCESS: 'READ_PEER_REVIEW_SUCCESS',
  READ_PEER_REVIEW_FAIL: 'READ_PEER_REVIEW_FAIL',

  READ_PEER_REVIEW_WITH_PROBLEM_START: 'READ_PEER_REVIEW_WITH_PROBLEM_START',
  READ_PEER_REVIEW_WITH_PROBLEM_SUCCESS: 'READ_PEER_REVIEW_WITH_PROBLEM_SUCCESS',
  READ_PEER_REVIEW_WITH_PROBLEM_FAIL: 'READ_PEER_REVIEW_WITH_PROBLEM_FAIL',

  EDIT_PEER_REVIEW_START: 'EDIT_PEER_REVIEW_START',
  EDIT_PEER_REVIEW_SUCCESS: 'EDIT_PEER_REVIEW_SUCCESS',
  EDIT_PEER_REVIEW_FAIL: 'EDIT_PEER_REVIEW_FAIL',

  DELETE_PEER_REVIEW_START: 'DELETE_PEER_REVIEW_START',
  DELETE_PEER_REVIEW_SUCCESS: 'DELETE_PEER_REVIEW_SUCCESS',
  DELETE_PEER_REVIEW_FAIL: 'DELETE_PEER_REVIEW_FAIL',

  BROWSE_PEER_REVIEW_RECORD_START: 'BROWSE_PEER_REVIEW_RECORD_START',
  BROWSE_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_PEER_REVIEW_RECORD_FAIL: 'BROWSE_PEER_REVIEW_RECORD_FAIL',

  READ_PEER_REVIEW_RECORD_START: 'READ_PEER_REVIEW_RECORD_START',
  READ_PEER_REVIEW_RECORD_SUCCESS: 'READ_PEER_REVIEW_RECORD_SUCCESS',
  READ_PEER_REVIEW_RECORD_FAIL: 'READ_PEER_REVIEW_RECORD_FAIL',

  SUBMIT_PEER_REVIEW_RECORD_START: 'SUBMIT_PEER_REVIEW_RECORD_START',
  SUBMIT_PEER_REVIEW_RECORD_SUCCESS: 'SUBMIT_PEER_REVIEW_RECORD_SUCCESS',
  SUBMIT_PEER_REVIEW_RECORD_FAIL: 'SUBMIT_PEER_REVIEW_RECORD_FAIL',

  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_START: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_START',
  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_FAIL: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_FAIL',

  BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_START: 'BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_START',
  BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_FAIL: 'BROWSE_ACCOUNT_ALL_PEER_REVIEW_RECORD_FAIL',

  ASSIGN_PEER_REVIEW_RECORD_START: 'ASSIGN_PEER_REVIEW_RECORD_START',
  ASSIGN_PEER_REVIEW_RECORD_SUCCESS: 'ASSIGN_PEER_REVIEW_RECORD_SUCCESS',
  ASSIGN_PEER_REVIEW_RECORD_FAIL: 'ASSIGN_PEER_REVIEW_RECORD_FAIL',

  GET_TARGET_PROBLEM_CHALLENGE_ID_START: 'GET_TARGET_PROBLEM_CHALLENGE_ID_START',
  GET_TARGET_PROBLEM_CHALLENGE_ID_SUCCESS: 'GET_TARGET_PROBLEM_CHALLENGE_ID_SUCCESS',
  GET_TARGET_PROBLEM_CHALLENGE_ID_FAIL: 'GET_TARGET_PROBLEM_CHALLENGE_ID_FAIL',
};
