export const viewConstants = {
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL',

  BROWSE_CLASS_MEMBER_START: 'BROWSE_CLASS_MEMBER_START',
  BROWSE_CLASS_MEMBER_SUCCESS: 'BROWSE_CLASS_MEMBER_SUCCESS',
  BROWSE_CLASS_MEMBER_FAIL: 'BROWSE_CLASS_MEMBER_FAIL',

  BROWSE_SUBMISSION_UNDER_CLASS_START: 'BROWSE_SUBMISSION_UNDER_CLASS_START',
  BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS: 'BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS',
  BROWSE_SUBMISSION_UNDER_CLASS_FAIL: 'BROWSE_SUBMISSION_UNDER_CLASS_FAIL',

  BROWSE_MYSUBMISSION_START: 'BROWSE_MYSUBMISSION_START',
  BROWSE_MYSUBMISSION_SUCCESS: 'BROWSE_MYSUBMISSION_SUCCESS',
  BROWSE_MYSUBMISSION_FAIL: 'BROWSE_MYSUBMISSION_FAIL',

  BROWSE_ACCESS_LOG_START: 'BROWSE_ACCESS_LOG_START',
  BROWSE_ACCESS_LOG_SUCCESS: 'BROWSE_ACCESS_LOG_SUCCESS',
  BROWSE_ACCESS_LOG_FAIL: 'BROWSE_ACCESS_LOG_FAIL',
};

export const courseConstants = {};
