export const viewConstants = {
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_START',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_SUCCESS',
  BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL: 'BROWSE_ACCOUNT_WITH_DEFAULT_STUDENT_ID_FAIL',

  BROWSE_CLASS_MEMBER_START: 'BROWSE_CLASS_MEMBER_START',
  BROWSE_CLASS_MEMBER_SUCCESS: 'BROWSE_CLASS_MEMBER_SUCCESS',
  BROWSE_CLASS_MEMBER_FAIL: 'BROWSE_CLASS_MEMBER_FAIL',

  BROWSE_SUBMISSION_UNDER_CLASS_START: 'BROWSE_SUBMISSION_UNDER_CLASS_START',
  BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS: 'BROWSE_SUBMISSION_UNDER_CLASS_SUCCESS',
  BROWSE_SUBMISSION_UNDER_CLASS_FAIL: 'BROWSE_SUBMISSION_UNDER_CLASS_FAIL',

  BROWSE_MY_SUBMISSION_START: 'BROWSE_MY_SUBMISSION_START',
  BROWSE_MY_SUBMISSION_SUCCESS: 'BROWSE_MY_SUBMISSION_SUCCESS',
  BROWSE_MY_SUBMISSION_FAIL: 'BROWSE_MY_SUBMISSION_FAIL',

  BROWSE_MY_SUBMISSION_UNDER_PROBLEM_START: 'BROWSE_MY_SUBMISSION_UNDER_PROBLEM_START',
  BROWSE_MY_SUBMISSION_UNDER_PROBLEM_SUCCESS: 'BROWSE_MY_SUBMISSION_UNDER_PROBLEM_SUCCESS',
  BROWSE_MY_SUBMISSION_UNDER_PROBLEM_FAIL: 'BROWSE_MY_SUBMISSION_UNDER_PROBLEM_FAIL',

  BROWSE_ACCESS_LOG_START: 'BROWSE_ACCESS_LOG_START',
  BROWSE_ACCESS_LOG_SUCCESS: 'BROWSE_ACCESS_LOG_SUCCESS',
  BROWSE_ACCESS_LOG_FAIL: 'BROWSE_ACCESS_LOG_FAIL',

  BROWSE_PEER_REVIEW_SUMMARY_REVIEW_START: 'BROWSE_PEER_REVIEW_SUMMARY_REVIEW_START',
  BROWSE_PEER_REVIEW_SUMMARY_REVIEW_SUCCESS: 'BROWSE_PEER_REVIEW_SUMMARY_REVIEW_SUCCESS',
  BROWSE_PEER_REVIEW_SUMMARY_REVIEW_FAIL: 'BROWSE_PEER_REVIEW_SUMMARY_REVIEW_FAIL',

  BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_START: 'BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_START',
  BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_SUCCESS: 'BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_SUCCESS',
  BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_FAIL: 'BROWSE_PEER_REVIEW_SUMMARY_RECEIVE_FAIL',

  BROWSE_CLASS_GRADE_START: 'BROWSE_CLASS_GRADE_START',
  BROWSE_CLASS_GRADE_SUCCESS: 'BROWSE_CLASS_GRADE_SUCCESS',
  BROWSE_CLASS_GRADE_FAIL: 'BROWSE_CLASS_GRADE_FAIL',

  BROWSE_ALL_PEER_REVIEW_REVIEW_START: 'BROWSE_ALL_PEER_REVIEW_REVIEW_START',
  BROWSE_ALL_PEER_REVIEW_REVIEW_SUCCESS: 'BROWSE_ALL_PEER_REVIEW_REVIEW_SUCCESS',
  BROWSE_ALL_PEER_REVIEW_REVIEW_FAIL: 'BROWSE_ALL_PEER_REVIEW_REVIEW_FAIL',

  BROWSE_ALL_PEER_REVIEW_RECEIVE_START: 'BROWSE_ALL_PEER_REVIEW_RECEIVE_START',
  BROWSE_ALL_PEER_REVIEW_RECEIVE_SUCCESS: 'BROWSE_ALL_PEER_REVIEW_RECEIVE_SUCCESS',
  BROWSE_ALL_PEER_REVIEW_RECEIVE_FAIL: 'BROWSE_ALL_PEER_REVIEW_RECEIVE_FAIL',
};

export const judgementConstants = {
  BROWSE_ALL_JUDGEMENT_JUDGE_CASE_START: 'BROWSE_ALL_JUDGEMENT_JUDGE_CASE_START',
  BROWSE_ALL_JUDGEMENT_JUDGE_CASE_SUCCESS: 'BROWSE_ALL_JUDGEMENT_JUDGE_CASE_SUCCESS',
  BROWSE_ALL_JUDGEMENT_JUDGE_CASE_FAIL: 'BROWSE_ALL_JUDGEMENT_JUDGE_CASE_FAIL',
};

export const courseConstants = {};

export const peerReviewConstants = {
  READ_PEER_REVIEW_START: 'READ_PEER_REVIEW_START',
  READ_PEER_REVIEW_SUCCESS: 'READ_PEER_REVIEW_SUCCESS',
  READ_PEER_REVIEW_FAIL: 'READ_PEER_REVIEW_FAIL',

  READ_PEER_REVIEW_WITH_PROBLEM_START: 'READ_PEER_REVIEW_WITH_PROBLEM_START',
  READ_PEER_REVIEW_WITH_PROBLEM_SUCCESS: 'READ_PEER_REVIEW_WITH_PROBLEM_SUCCESS',
  READ_PEER_REVIEW_WITH_PROBLEM_FAIL: 'READ_PEER_REVIEW_WITH_PROBLEM_FAIL',

  EDIT_PEER_REVIEW_START: 'EDIT_PEER_REVIEW_START',
  EDIT_PEER_REVIEW_SUCCESS: 'EDIT_PEER_REVIEW_SUCCESS',
  EDIT_PEER_REVIEW_FAIL: 'EDIT_PEER_REVIEW_FAIL',

  DELETE_PEER_REVIEW_START: 'DELETE_PEER_REVIEW_START',
  DELETE_PEER_REVIEW_SUCCESS: 'DELETE_PEER_REVIEW_SUCCESS',
  DELETE_PEER_REVIEW_FAIL: 'DELETE_PEER_REVIEW_FAIL',

  BROWSE_PEER_REVIEW_RECORD_START: 'BROWSE_PEER_REVIEW_RECORD_START',
  BROWSE_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_PEER_REVIEW_RECORD_FAIL: 'BROWSE_PEER_REVIEW_RECORD_FAIL',

  READ_PEER_REVIEW_RECORD_START: 'READ_PEER_REVIEW_RECORD_START',
  READ_PEER_REVIEW_RECORD_SUCCESS: 'READ_PEER_REVIEW_RECORD_SUCCESS',
  READ_PEER_REVIEW_RECORD_FAIL: 'READ_PEER_REVIEW_RECORD_FAIL',

  SUBMIT_PEER_REVIEW_RECORD_START: 'SUBMIT_PEER_REVIEW_RECORD_START',
  SUBMIT_PEER_REVIEW_RECORD_SUCCESS: 'SUBMIT_PEER_REVIEW_RECORD_SUCCESS',
  SUBMIT_PEER_REVIEW_RECORD_FAIL: 'SUBMIT_PEER_REVIEW_RECORD_FAIL',

  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_START: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_START',
  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_FAIL: 'BROWSE_ACCOUNT_REVIEWED_PEER_REVIEW_RECORD_FAIL',

  BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_START: 'BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_START',
  BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_FAIL: 'BROWSE_ACCOUNT_ALL_REVIEWWD_PEER_REVIEW_RECORD_FAIL',

  ASSIGN_PEER_REVIEW_RECORD_START: 'ASSIGN_PEER_REVIEW_RECORD_START',
  ASSIGN_PEER_REVIEW_RECORD_SUCCESS: 'ASSIGN_PEER_REVIEW_RECORD_SUCCESS',
  ASSIGN_PEER_REVIEW_RECORD_FAIL: 'ASSIGN_PEER_REVIEW_RECORD_FAIL',

  BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_START: 'BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_START',
  BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_SUCCESS: 'BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_SUCCESS',
  BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_FAIL: 'BROWSE_ACCOUNT_RECEIVED_PEER_REVIEW_RECORD_FAIL',
};

export const scoreboardConstants = {
  ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_START: 'ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_START',
  ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_SUCCESS: 'ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_SUCCESS',
  ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_FAIL: 'ADD_TEAM_PROJECT_SCOREBOARD_UNDER_CHALLENGE_FAIL',

  READ_SCOREBOARD_START: 'READ_SCOREBOARD_START',
  READ_SCOREBOARD_SUCCESS: 'READ_SCOREBOARD_SUCCESS',
  READ_SCOREBOARD_FAIL: 'READ_SCOREBOARD_FAIL',

  EDIT_TEAM_PROJECT_SCOREBOARD_START: 'EDIT_TEAM_PROJECT_SCOREBOARD_START',
  EDIT_TEAM_PROJECT_SCOREBOARD_SUCCESS: 'EDIT_TEAM_PROJECT_SCOREBOARD_SUCCESS',
  EDIT_TEAM_PROJECT_SCOREBOARD_FAIL: 'EDIT_TEAM_PROJECT_SCOREBOARD_FAIL',

  DELETE_SCOREBOARD_START: 'DELETE_SCOREBOARD_START',
  DELETE_SCOREBOARD_SUCCESS: 'DELETE_SCOREBOARD_SUCCESS',
  DELETE_SCOREBOARD_FAIL: 'DELETE_SCOREBOARD_FAIL',

  VIEW_TEAM_PROJECT_SCOREBOARD_START: 'VIEW_TEAM_PROJECT_SCOREBOARD_START',
  VIEW_TEAM_PROJECT_SCOREBOARD_SUCCESS: 'VIEW_TEAM_PROJECT_SCOREBOARD_SUCCESS',
  VIEW_TEAM_PROJECT_SCOREBOARD_FAIL: 'VIEW_TEAM_PROJECT_SCOREBOARD_FAIL',
};
