// eslint-disable-next-line import/prefer-default-export
export const challengeConstants = {
  FETCH_CHALLENGES_REQUEST: 'FETCH_CHALLENGES_REQUEST',
  FETCH_CHALLENGES_SUCCESS: 'FETCH_CHALLENGES_SUCCESS',
  FETCH_CHALLENGES_FAIL: 'FETCH_CHALLENGES_FAIL',

  ADD_CHALLENGE_REQUEST: 'ADD_CHALLENGE_REQUEST',
  ADD_CHALLENGE_SUCCESS: 'ADD_CHALLENGE_SUCCESS',
  ADD_CHALLENGE_FAIL: 'ADD_CHALLENGE_FAIL',

  EDIT_CHALLENGE_REQUEST: 'EDIT_CHALLENGE_REQUEST',
  EDIT_CHALLENGE_SUCCESS: 'EDIT_CHALLENGE_SUCCESS',
  EDIT_CHALLENGE_FAIL: 'EDIT_CHALLENGE_FAIL',

  DELETE_CHALLENGE_REQUEST: 'DELETE_CHALLENGE_REQUEST',
  DELETE_CHALLENGE_SUCCESS: 'DELETE_CHALLENGE_SUCCESS',
  DELETE_CHALLENGE_FAIL: 'DELETE_CHALLENGE_FAIL',

  ADD_PROBLEM_START: 'ADD_PROBLEM_START',
  ADD_PROBLEM_SUCCESS: 'ADD_PROBLEM_SUCCESS',
  ADD_PROBLEM_FAIL: 'ADD_PROBLEM_FAIL',

  ADD_ESSAY_START: 'ADD_ESSAY_START',
  ADD_ESSAY_SUCCESS: 'ADD_ESSAY_SUCCESS',
  ADD_ESSAY_FAIL: 'ADD_ESSAY_FAIL',

  ADD_PEER_REVIEW_START: 'ADD_PEER_REVIEW_START',
  ADD_PEER_REVIEW_SUCCESS: 'ADD_PEER_REVIEW_SUCCESS',
  ADD_PEER_REVIEW_FAIL: 'ADD_PEER_REVIEW_FAIL',

  FETCH_CHALLENGE_SUMMARY_REQUEST: 'FETCH_CHALLENGE_SUMMARY_REQUEST',
  FETCH_CHALLENGE_SUMMARY_SUCCESS: 'FETCH_CHALLENGE_SUMMARY_SUCCESS',
  FETCH_CHALLENGE_SUMMARY_FAIL: 'FETCH_CHALLENGE_SUMMARY_FAIL',

  FETCH_CHALLENGE_MEMBER_SUBMISSION_REQUEST: 'FETCH_CHALLENGE_MEMBER_SUBMISSION_REQUEST',
  FETCH_CHALLENGE_MEMBER_SUBMISSION_SUCCESS: 'FETCH_CHALLENGE_MEMBER_SUBMISSION_SUCCESS',
  FETCH_CHALLENGE_MEMBER_SUBMISSION_FAIL: 'FETCH_CHALLENGE_MEMBER_SUBMISSION_FAIL',

  BROWSE_TASKS_UNDER_CHALLENGE_START: 'BROWSE_TASKS_UNDER_CHALLENGE_START',
  BROWSE_TASKS_UNDER_CHALLENGE_SUCCESS: 'BROWSE_TASKS_UNDER_CHALLENGE_SUCCESS',
  BROWSE_TASKS_UNDER_CHALLENGE_FAIL: 'BROWSE_TASKS_UNDER_CHALLENGE_FAIL',
};

export const gradeConstants = {
  FETCH_CLASS_GRADE_START: 'FETCH_CLASS_GRADE_START',
  FETCH_CLASS_GRADE_SUCCESS: 'FETCH_CLASS_GRADE_SUCCESS',
  FETCH_CLASS_GRADE_FAIL: 'FETCH_CLASS_GRADE_FAIL',

  ADD_CLASS_GRADE_START: 'ADD_CLASS_GRADE_START',
  ADD_CLASS_GRADE_SUCCESS: 'ADD_CLASS_GRADE_SUCCESS',
  ADD_CLASS_GRADE_FAIL: 'ADD_CLASS_GRADE_FAIL',

  FETCH_ACCOUNT_GRADE_START: 'FETCH_ACCOUNT_GRADE_START',
  FETCH_ACCOUNT_GRADE_SUCCESS: 'FETCH_ACCOUNT_GRADE_SUCCESS',
  FETCH_ACCOUNT_GRADE_FAIL: 'FETCH_ACCOUNT_GRADE_FAIL',

  DOWNLOAD_GRADE_FILE_START: 'DOWNLOAD_GRADE_FILE_START',
  DOWNLOAD_GRADE_FILE_SUCCESS: 'DOWNLOAD_GRADE_FILE_SUCCESS',
  DOWNLOAD_GRADE_FILE_FAIL: 'DOWNLOAD_GRADE_FILE_FAIL',

  DELETE_GRADE_START: 'DELETE_GRADE_START',
  DELETE_GRADE_SUCCESS: 'DELETE_GRADE_SUCCESS',
  DELETE_GRADE_FAIL: 'DELETE_GRADE_FAIL',

  EDIT_GRADE_START: 'EDIT_GRADE_START',
  EDIT_GRADE_SUCCESS: 'EDIT_GRADE_SUCCESS',
  EDIT_GRADE_FAIL: 'EDIT_GRADE_FAIL',
};

export const teamConstants = {
  FETCH_TEAMS_START: 'FETCH_TEAMS_START',
  FETCH_TEAMS_SUCCESS: 'FETCH_TEAMS_SUCCESS',
  FETCH_TEAMS_FAIL: 'FETCH_TEAMS_FAIL',

  ADD_TEAM_START: 'ADD_TEAM_START',
  ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
  ADD_TEAM_FAIL: 'ADD_TEAM_FAIL',

  IMPORT_TEAM_START: 'IMPORT_TEAM_START',
  IMPORT_TEAM_SUCCESS: 'IMPORT_TEAM_SUCCESS',
  IMPORT_TEAM_FAIL: 'IMPORT_TEAM_FAIL',

  DOWNLOAD_TEAM_FILE_START: 'DOWNLOAD_TEAM_FILE_START',
  DOWNLOAD_TEAM_FILE_SUCCESS: 'DOWNLOAD_TEAM_FILE_SUCCESS',
  DOWNLOAD_TEAM_FILE_FAIL: 'DOWNLOAD_TEAM_FILE_FAIL',

  EDIT_TEAM_START: 'EDIT_TEAM_START',
  EDIT_TEAM_SUCCESS: 'EDIT_TEAM_SUCCESS',
  EDIT_TEAM_FAIL: 'EDIT_TEAM_FAIL',

  FETCH_TEAM_MEMBER_START: 'FETCH_TEAM_MEMBER_START',
  FETCH_TEAM_MEMBER_SUCCESS: 'FETCH_TEAM_MEMBER_SUCCESS',
  FETCH_TEAM_MEMBER_FAIL: 'FETCH_TEAM_MEMBER_FAIL',

  ADD_TEAM_MEMBER_START: 'ADD_TEAM_MEMBER_START',
  ADD_TEAM_MEMBER_SUCCESS: 'ADD_TEAM_MEMBER_SUCCESS',
  ADD_TEAM_MEMBER_FAIL: 'ADD_TEAM_MEMBER_FAIL',

  EDIT_TEAM_MEMBER_START: 'EDIT_TEAM_MEMBER_START',
  EDIT_TEAM_MEMBER_SUCCESS: 'EDIT_TEAM_MEMBER_SUCCESS',
  EDIT_TEAM_MEMBER_FAIL: 'EDIT_TEAM_MEMBER_FAIL',

  DELETE_TEAM_MEMBER_START: 'DELETE_TEAM_MEMBER_START',
  DELETE_TEAM_MEMBER_SUCCESS: 'DELETE_TEAM_MEMBER_SUCCESS',
  DELETE_TEAM_MEMBER_FAIL: 'DELETE_TEAM_MEMBER_FAIL',
};

export const problemConstants = {
  READ_PROBLEM_START: 'READ_PROBLEM_START',
  READ_PROBLEM_SUCCESS: 'READ_PROBLEM_SUCCESS',
  READ_PROBLEM_FAIL: 'READ_PROBLEM_FAIL',

  DELETE_PROBLEM_START: 'DELETE_PROBLEM_START',
  DELETE_PROBLEM_SUCCESS: 'DELETE_PROBLEM_SUCCESS',
  DELETE_PROBLEM_FAIL: 'DELETE_PROBLEM_FAIL',

  EDIT_PROBLEM_START: 'EDIT_PROBLEM_START',
  EDIT_PROBLEM_SUCCESS: 'EDIT_PROBLEM_SUCCESS',
  EDIT_PROBLEM_FAIL: 'EDIT_PROBLEM_FAIL',

  FETCH_TESTCASE_UNDER_PROBLEM_START: 'FETCH_TESTCASE_UNDER_PROBLEM_START',
  FETCH_TESTCASE_UNDER_PROBLEM_SUCCESS: 'FETCH_TESTCASE_UNDER_PROBLEM_SUCCESS',
  FETCH_TESTCASE_UNDER_PROBLEM_FAIL: 'FETCH_TESTCASE_UNDER_PROBLEM_FAIL',

  ADD_TESTCASE_UNDER_PROBLEM_START: 'ADD_TESTCASE_UNDER_PROBLEM_START',
  ADD_TESTCASE_UNDER_PROBLEM_SUCCESS: 'ADD_TESTCASE_UNDER_PROBLEM_SUCCESS',
  ADD_TESTCASE_UNDER_PROBLEM_FAIL: 'ADD_TESTCASE_UNDER_PROBLEM_FAIL',

  BROWSE_ASSISTING_DATA_START: 'BROWSE_ASSISTING_DATA_START',
  BROWSE_ASSISTING_DATA_SUCCESS: 'BROWSE_ASSISTING_DATA_SUCCESS',
  BROWSE_ASSISTING_DATA_FAIL: 'BROWSE_ASSISTING_DATA_FAIL',

  SUBMIT_PROBLEM_START: 'SUBMIT_PROBLEM_START',
  SUBMIT_PROBLEM_SUCCESS: 'SUBMIT_PROBLEM_SUCCESS',
  SUBMIT_PROBLEM_FAIL: 'SUBMIT_PROBLEM_FAIL',

  READ_TESTCASE_START: 'READ_TESTCASE_START',
  READ_TESTCASE_SUCCESS: 'READ_TESTCASE_SUCCESS',
  READ_TESTCASE_FAIL: 'READ_TESTCASE_FAIL',

  DELETE_TESTCASE_START: 'DELETE_TESTCASE_START',
  DELETE_TESTCASE_SUCCESS: 'DELETE_TESTCASE_SUCCESS',
  DELETE_TESTCASE_FAIL: 'DELETE_TESTCASE_FAIL',

  EDIT_TESTCASE_START: 'EDIT_TESTCASE_START',
  EDIT_TESTCASE_SUCCESS: 'EDIT_TESTCASE_SUCCESS',
  EDIT_TESTCASE_FAIL: 'EDIT_TESTCASE_FAIL',

  UPLOAD_TESTCASE_INPUT_START: 'UPLOAD_TESTCASE_INPUT_START',
  UPLOAD_TESTCASE_INPUT_SUCCESS: 'UPLOAD_TESTCASE_INPUT_SUCCESS',
  UPLOAD_TESTCASE_INPUT_FAIL: 'UPLOAD_TESTCASE_INPUT_FAIL',

  UPLOAD_TESTCASE_OUTPUT_START: 'UPLOAD_TESTCASE_OUTPUT_START',
  UPLOAD_TESTCASE_OUTPUT_SUCCESS: 'UPLOAD_TESTCASE_OUTPUT_SUCCESS',
  UPLOAD_TESTCASE_OUTPUT_FAIL: 'UPLOAD_TESTCASE_OUTPUT_FAIL',

  ADD_TESTCASE_START: 'ADD_TESTCASE_START',
  ADD_TESTCASE_SUCCESS: 'ADD_TESTCASE_SUCCESS',
  ADD_TESTCASE_FAIL: 'ADD_TESTCASE_FAIL',

  READ_SUBMISSION_START: 'READ_SUBMISSION_START',
  READ_SUBMISSION_SUCCESS: 'READ_SUBMISSION_SUCCESS',
  READ_SUBMISSION_FAIL: 'READ_SUBMISSION_FAIL',

  READ_SUBMISSION_JUDGE_START: 'READ_SUBMISSION_JUDGE_START',
  READ_SUBMISSION_JUDGE_SUCCESS: 'READ_SUBMISSION_JUDGE_SUCCESS',
  READ_SUBMISSION_JUDGE_FAIL: 'READ_SUBMISSION_JUDGE_FAIL',

  BROWSE_JUDGE_CASES_START: 'BROWSE_JUDGE_CASES_START',
  BROWSE_JUDGE_CASES_SUCCESS: 'BROWSE_JUDGE_CASES_SUCCESS',
  BROWSE_JUDGE_CASES_FAIL: 'BROWSE_JUDGE_CASES_FAIL',

  DELETE_ASSISTING_DATA_START: 'DELETE_ASSISTING_DATA_START',
  DELETE_ASSISTING_DATA_SUCCESS: 'DELETE_ASSISTING_DATA_SUCCESS',
  DELETE_ASSISTING_DATA_FAIL: 'DELETE_ASSISTING_DATA_FAIL',

  EDIT_ASSISTING_DATA_START: 'EDIT_ASSISTING_DATA_START',
  EDIT_ASSISTING_DATA_SUCCESS: 'EDIT_ASSISTING_DATA_SUCCESS',
  EDIT_ASSISTING_DATA_FAIL: 'EDIT_ASSISTING_DATA_FAIL',

  ADD_ASSISTING_DATA_START: 'ADD_ASSISTING_DATA_START',
  ADD_ASSISTING_DATA_SUCCESS: 'ADD_ASSISTING_DATA_SUCCESS',
  ADD_ASSISTING_DATA_FAIL: 'ADD_ASSISTING_DATA_FAIL',

  READ_PROBLEM_SCORE_START: 'READ_PROBLEM_SCORE_START',
  READ_PROBLEM_SCORE_SUCCESS: 'READ_PROBLEM_SCORE_SUCCESS',
  READ_PROBLEM_SCORE_FAIL: 'READ_PROBLEM_SCORE_FAIL',
};

export const memberConstants = {};

export const submissionConstants = {
  FETCH_ALL_SUBMISSIONS_START: 'FETCH_ALL_SUBMISSIONS_START',
  FETCH_ALL_SUBMISSIONS_SUCCESS: 'FETCH_ALL_SUBMISSIONS_SUCCESS',
  FETCH_ALL_SUBMISSIONS_FAIL: 'FETCH_ALL_SUBMISSIONS_FAIL',

  FETCH_SUBMISSION_START: 'FETCH_SUBMISSION_START',
  FETCH_SUBMISSION_SUCCESS: 'FETCH_SUBMISSION_SUCCESS',
  FETCH_SUBMISSION_FAIL: 'FETCH_SUBMISSION_FAIL',

  FETCH_SUBMISSIONS_START: 'FETCH_SUBMISSIONS_START',
  FETCH_SUBMISSIONS_SUCCESS: 'FETCH_SUBMISSIONS_SUCCESS',
  FETCH_SUBMISSIONS_FAIL: 'FETCH_SUBMISSIONS_FAIL',

  ADD_SUBMISSION_START: 'ADD_SUBMISSION_START',
  ADD_SUBMISSION_SUCCESS: 'ADD_SUBMISSION_SUCCESS',
  ADD_SUBMISSION_FAIL: 'ADD_SUBMISSION_FAIL',

  FETCH_JUDGEMENT_START: 'FETCH_JUDGEMENT_START',
  FETCH_JUDGEMENT_SUCCESS: 'FETCH_JUDGEMENT_SUCCESS',
  FETCH_JUDGEMENT_FAIL: 'FETCH_JUDGEMENT_FAIL',

  READ_SUBMISSION_JUDGE_START: 'READ_SUBMISSION_JUDGE_START',
  READ_SUBMISSION_JUDGE_SUCCESS: 'READ_SUBMISSION_JUDGE_SUCCESS',
  READ_SUBMISSION_JUDGE_FAIL: 'READ_SUBMISSION_JUDGE_FAIL',

  BROWSE_JUDGE_CASES_START: 'BROWSE_JUDGE_CASES_START',
  BROWSE_JUDGE_CASES_SUCCESS: 'BROWSE_JUDGE_CASES_SUCCESS',
  BROWSE_JUDGE_CASES_FAIL: 'BROWSE_JUDGE_CASES_FAIL',

  READ_TESTCASE_START: 'READ_TESTCASE_START',
  READ_TESTCASE_SUCCESS: 'READ_TESTCASE_SUCCESS',
  READ_TESTCASE_FAIL: 'READ_TESTCASE_FAIL',

  GET_ACCOUNT_BATCH_START: 'GET_ACCOUNT_BATCH_START',
  GET_ACCOUNT_BATCH_SUCCESS: 'GET_ACCOUNT_BATCH_SUCCESS',
  GET_ACCOUNT_BATCH_FAIL: 'GET_ACCOUNT_BATCH_FAIL',
};

export const essayConstants = {
  READ_ESSAY_START: 'READ_ESSAY_START',
  READ_ESSAY_SUCCESS: 'READ_ESSAY_SUCCESS',
  READ_ESSAY_FAIL: 'READ_ESSAY_FAIL',

  ADD_ESSAY_START: 'ADD_ESSAY_START',
  ADD_ESSAY_SUCCESS: 'ADD_ESSAY_SUCCESS',
  ADD_ESSAY_FAIL: 'ADD_ESSAY_FAIL',

  EDIT_ESSAY_START: 'EDIT_ESSAY_START',
  EDIT_ESSAY_SUCCESS: 'EDIT_ESSAY_SUCCESS',
  EDIT_ESSAY_FAIL: 'EDIT_ESSAY_FAIL',

  DELETE_ESSAY_START: 'DELETE_ESSAY_START',
  DELETE_ESSAY_SUCCESS: 'DELETE_ESSAY_SUCCESS',
  DELETE_ESSAY_FAIL: 'DELETE_ESSAY_FAIL',

  BROWSE_ESSAY_SUBMISSION_START: 'BROWSE_ESSAY_SUBMISSION_START:',
  BROWSE_ESSAY_SUBMISSION_SUCCESS: 'BROWSE_ESSAY_SUBMISSION_SUCCESS',
  BROWSE_ESSAY_SUBMISSION_FAIL: 'BROWSE_ESSAY_SUBMISSION_FAIL',

  UPLOAD_ESSAY_SUBMISSION_START: 'UPLOAD_ESSAY_SUBMISSION_START',
  UPLOAD_ESSAY_SUBMISSION_SUCCESS: 'UPLOAD_ESSAY_SUBMISSION_SUCCESS',
  UPLOAD_ESSAY_SUBMISSION_FAIL: 'UPLOAD_ESSAY_SUBMISSION_FAIL',

  READ_ESSAY_SUBMISSION_START: 'READ_ESSAY_SUBMISSION_START',
  READ_ESSAY_SUBMISSION_SUCCESS: 'READ_ESSAY_SUBMISSION_SUCCESS',
  READ_ESSAY_SUBMISSION_FAIL: 'READ_ESSAY_SUBMISSION_FAIL',

  REUPLOAD_ESSAY_SUBMISSION_START: 'REUPLOAD_ESSAY_SUBMISSION_START',
  REUPLOAD_ESSAY_SUBMISSION_SUCCESS: 'REUPLOAD_ESSAY_SUBMISSION_SUCCESS',
  REUPLOAD_ESSAY_SUBMISSION_FAIL: 'REUPLOAD_ESSAY_SUBMISSION_FAIL',
};
