// eslint-disable-next-line import/prefer-default-export
export const challengeConstants = {
  FETCH_CHALLENGES_REQUEST: 'FETCH_CHALLENGES_REQUEST',
  FETCH_CHALLENGES_SUCCESS: 'FETCH_CHALLENGES_SUCCESS',
  FETCH_CHALLENGES_FAIL: 'FETCH_CHALLENGES_FAIL',

  ADD_CHALLENGE_REQUEST: 'ADD_CHALLENGE_REQUEST',
  ADD_CHALLENGE_SUCCESS: 'ADD_CHALLENGE_SUCCESS',
  ADD_CHALLENGE_FAIL: 'ADD_CHALLENGE_FAIL',
};

export const gradeConstants = {
  FETCH_CLASS_GRADE_START: 'FETCH_CLASS_GRADE_START',
  FETCH_CLASS_GRADE_SUCCESS: 'FETCH_CLASS_GRADE_SUCCESS',
  FETCH_CLASS_GRADE_FAIL: 'FETCH_CLASS_GRADE_FAIL',

  ADD_CLASS_GRADE_START: 'ADD_CLASS_GRADE_START',
  ADD_CLASS_GRADE_SUCCESS: 'ADD_CLASS_GRADE_SUCCESS',
  ADD_CLASS_GRADE_FAIL: 'ADD_CLASS_GRADE_FAIL',

  FETCH_ACCOUNT_GRADE_START: 'FETCH_ACCOUNT_GRADE_START',
  FETCH_ACCOUNT_GRADE_SUCCESS: 'FETCH_ACCOUNT_GRADE_SUCCESS',
  FETCH_ACCOUNT_GRADE_FAIL: 'FETCH_ACCOUNT_GRADE_FAIL',

  FETCH_GRADE_START: 'FETCH_GRADE_START',
  FETCH_GRADE_SUCCESS: 'FETCH_GRADE_SUCCESS',
  FETCH_GRADE_FAIL: 'FETCH_GRADE_FAIL',

  DELETE_GRADE_START: 'DELETE_GRADE_START',
  DELETE_GRADE_SUCCESS: 'DELETE_GRADE_SUCCESS',
  DELETE_GRADE_FAIL: 'DELETE_GRADE_FAIL',

  EDIT_GRADE_START: 'EDIT_GRADE_START',
  EDIT_GRADE_SUCCESS: 'EDIT_GRADE_SUCCESS',
  EDIT_GRADE_FAIL: 'EDIT_GRADE_FAIL',
};

export const teamConstants = {
  FETCH_CLASS_TEAM_START: 'FETCH_CLASS_TEAM_START',
  FETCH_CLASS_TEAM_SUCCESS: 'FETCH_CLASS_TEAM_SUCCESS',
  FETCH_CLASS_TEAM_FAIL: 'FETCH_CLASS_TEAM_FAIL',

  ADD_CLASS_TEAM_START: 'ADD_CLASS_TEAM_START',
  ADD_CLASS_TEAM_SUCCESS: 'ADD_CLASS_TEAM_SUCCESS',
  ADD_CLASS_TEAM_FAIL: 'ADD_CLASS_TEAM_FAIL',

  FETCH_TEAM_START: 'FETCH_TEAM_START',
  FETCH_TEAM_SUCCESS: 'FETCH_TEAM_SUCCESS',
  FETCH_TEAM_FAIL: 'FETCH_TEAM_FAIL',

  DELETE_TEAM_START: 'DELETE_TEAM_START',
  DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
  DELETE_TEAM_FAIL: 'DELETE_TEAM_FAIL',

  EDIT_TEAM_START: 'EDIT_TEAM_START',
  EDIT_TEAM_SUCCESS: 'EDIT_TEAM_SUCCESS',
  EDIT_TEAM_FAIL: 'EDIT_TEAM_FAIL',

  FETCH_TEAM_MEMBER_START: 'FETCH_TEAM_MEMBER_START',
  FETCH_TEAM_MEMBER_SUCCESS: 'FETCH_TEAM_MEMBER_SUCCESS',
  FETCH_TEAM_MEMBER_FAIL: 'FETCH_TEAM_MEMBER_FAIL',

  EDIT_TEAM_MEMBER_START: 'EDIT_TEAM_MEMBER_START',
  EDIT_TEAM_MEMBER_SUCCESS: 'EDIT_TEAM_MEMBER_SUCCESS',
  EDIT_TEAM_MEMBER_FAIL: 'EDIT_TEAM_MEMBER_FAIL',

  DELETE_TEAM_MEMBER_START: 'DELETE_TEAM_MEMBER_START',
  DELETE_TEAM_MEMBER_SUCCESS: 'DELETE_TEAM_MEMBER_SUCCESS',
  DELETE_TEAM_MEMBER_FAIL: 'DELETE_TEAM_MEMBER_FAIL',
};
