export const authConstants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',

  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  FORGET_USERNAME_START: 'FORGET_USERNAME_START',
  FORGET_USERNAME_SUCCESS: 'FORGET_USERNAME_SUCCESS',
  FORGET_USERNAME_FAIL: 'FORGET_USERNAME_FAIL',

  FORGET_PASSWORD_START: 'FORGET_PASSWORD_START',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAIL: 'FORGET_PASSWORD_FAIL',

  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',

  EMAIL_VERIFICATION_START: 'EMAIL_VERIFICATION_START',
  EMAIL_VERIFICATION_SUCCESS: 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_VERIFICATION_FAIL: 'EMAIL_VERIFICATION_FAIL',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};

export const userConstants = {
  EDIT_SELF_PASSWORD_START: 'EDIT_SELF_PASSWORD_START',
  EDIT_SELF_PASSWORD_SUCCESS: 'EDIT_SELF_PASSWORD_SUCCESS',
  EDIT_SELF_PASSWORD_FAIL: 'EDIT_SELF_PASSWORD_FAIL',

  EDIT_SELF_ACCOUNT_START: 'EDIT_SELF_ACCOUNT_START',
  EDIT_SELF_ACCOUNT_SUCCESS: 'EDIT_SELF_ACCOUNT_SUCCESS',
  EDIT_SELF_ACCOUNT_FAIL: 'EDIT_SELF_ACCOUNT_FAIL',

  MAKE_SELF_STUDENT_CARD_DEFAULT_START: 'MAKE_SELF_STUDENT_CARD_DEFAULT_START',
  MAKE_SELF_STUDENT_CARD_DEFAULT_SUCCESS: 'MAKE_SELF_STUDENT_CARD_DEFAULT_SUCCESS',
  MAKE_SELF_STUDENT_CARD_DEFAULT_FAIL: 'MAKE_SELF_STUDENT_CARD_DEFAULT_FAIL',

  GET_SELF_STUDENT_CARD_START: 'GET_SELF_STUDENT_CARD_START',
  GET_SELF_STUDENT_CARD_SUCCESS: 'GET_SELF_STUDENT_CARD_SUCCESS',
  GET_SELF_STUDENT_CARD_FAIL: 'GET_SELF_STUDENT_CARD_FAIL',

  ADD_SELF_STUDENT_CARD_START: 'ADD_SELF_STUDENT_CARD_START',
  ADD_SELF_STUDENT_CARD_SUCCESS: 'ADD_SELF_STUDENT_CARD_SUCCESS',
  ADD_SELF_STUDENT_CARD_FAIL: 'ADD_SELF_STUDENT_CARD_FAIL',

  USER_BROWSE_ANNOUNCEMENT_SUCCESS: 'USER_BROWSE_ANNOUNCEMENT_SUCCESS',
  USER_BROWSE_ANNOUNCEMENT_FAIL: 'USER_BROWSE_ANNOUNCEMENT_FAIL',
  USER_READ_NOTIFY: 'USER_READ_NOTIFY',
  USER_READ_NOTIFY_FAIL: 'USER_READ_NOTIFY_FAIL',

  BROWSE_SELF_PENDING_STUDENT_CARDS_START: 'BROWSE_SELF_PENDING_STUDENT_CARDS_START',
  BROWSE_SELF_PENDING_STUDENT_CARDS_SUCCESS: 'BROWSE_SELF_PENDING_STUDENT_CARDS_SUCCESS',
  BROWSE_SELF_PENDING_STUDENT_CARDS_FAIL: 'BROWSE_SELF_PENDING_STUDENT_CARDS_FAIL',

  RESEND_SELF_EMAIL_VERIFICATION_START: 'RESEND_SELF_EMAIL_VERIFICATION_START',
  RESEND_SELF_EMAIL_VERIFICATION_SUCCESS: 'RESEND_SELF_EMAIL_VERIFICATION_SUCCESS',
  RESEND_SELF_EMAIL_VERIFICATION_FAIL: 'RESEND_SELF_EMAIL_VERIFICATION_FAIL',

  DELETE_SELF_PENDING_STUDENT_CARD_START: 'DELETE_SELF_PENDING_STUDENT_CARD_START',
  DELETE_SELF_PENDING_STUDENT_CARD_SUCCESS: 'DELETE_SELF_PENDING_STUDENT_CARD_SUCCESS',
  DELETE_SELF_PENDING_STUDENT_CARD_FAIL: 'DELETE_SELF_PENDING_STUDENT_CARD_FAIL',

  READ_OTHERS_ACCOUNT_START: 'READ_OTHERS_ACCOUNT_START',
  READ_OTHERS_ACCOUNT_SUCCESS: 'READ_OTHERS_ACCOUNT_SUCCESS',
  READ_OTHERS_ACCOUNT_FAIL: 'READ_OTHERS_ACCOUNT_FAIL',
};
