export const authConstants = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  API_CALL_ERROR: 'API_CALL_ERROR',

  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  FORGET_PASSWORD_START: 'FORGET_PASSWORD_START',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_FAIL: 'FORGET_PASSWORD_FAIL',

  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
};

export const userConstants = {
  EDIT_SELF_PASSWORD_START: 'EDIT_SELF_PASSWORD_START',
  EDIT_SELF_PASSWORD_SUCCESS: 'EDIT_SELF_PASSWORD_SUCCESS',
  EDIT_SELF_PASSWORD_FAIL: 'EDIT_SELF_PASSWORD_FAIL',

  EDIT_SELF_ACCOUNT_START: 'EDIT_SELF_ACCOUNT_START',
  EDIT_SELF_ACCOUNT_SUCCESS: 'EDIT_SELF_ACCOUNT_SUCCESS',
  EDIT_SELF_ACCOUNT_FAIL: 'EDIT_SELF_ACCOUNT_FAIL',

  MAKE_SELF_STUDENT_CARD_DEFAULT_START: 'MAKE_SELF_STUDENT_CARD_DEFAULT_START',
  MAKE_SELF_STUDENT_CARD_DEFAULT_SUCCESS: 'MAKE_SELF_STUDENT_CARD_DEFAULT_SUCCESS',
  MAKE_SELF_STUDENT_CARD_DEFAULT_FAIL: 'MAKE_SELF_STUDENT_CARD_DEFAULT_FAIL',

  GET_SELF_STUDENT_CARD_START: 'GET_SELF_STUDENT_CARD_START',
  GET_SELF_STUDENT_CARD_SUCCESS: 'GET_SELF_STUDENT_CARD_SUCCESS',
  GET_SELF_STUDENT_CARD_FAIL: 'GET_SELF_STUDENT_CARD_FAIL',

  ADD_SELF_STUDENT_CARD_START: 'ADD_SELF_STUDENT_CARD_START',
  ADD_SELF_STUDENT_CARD_SUCCESS: 'ADD_SELF_STUDENT_CARD_SUCCESS',
  ADD_SELF_STUDENT_CARD_FAIL: 'ADD_SELF_STUDENT_CARD_FAIL',
};
