export const accountConstants = {
  FETCH_INSTITUTE_START: 'FETCH_INSTITUTE_START',
  FETCH_INSTITUTE_SUCCESS: 'FETCH_INSTITUTE_SUCCESS',
  FETCH_INSTITUTE_FAIL: 'FETCH_INSTITUTE_FAIL',

  ADD_INSTITUTE_START: 'ADD_INSTITUTE_START',
  ADD_INSTITUTE_SUCCESS: 'ADD_INSTITUTE_SUCCESS',
  ADD_INSTITUTE_FAIL: 'ADD_INSTITUTE_FAIL',

  EDIT_INSTITUTE_START: 'RENAME_INSTITUTE_START',
  EDIT_INSTITUTE_SUCCESS: 'RENAME_INSTITUTE_SUCCESS',
  EDIT_INSTITUTE_FAIL: 'RENAME_INSTITUTE_FAIL',

  FETCH_ACCOUNTS_START: 'FETCH_ACCOUNTS_START',
  FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
  FETCH_ACCOUNTS_FAIL: 'FETCH_ACCOUNTS_FAIL',

  EDIT_ACCOUNT_START: 'EDIT_ACCOUNT_START',
  EDIT_ACCOUNT_SUCCESS: 'EDIT_ACCOUNT_SUCCESS',
  EDIT_ACCOUNT_FAIL: 'EDIT_ACCOUNT_FAIL',

  DELETE_ACCOUNT_START: 'DELETE_ACCOUNT_START',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAIL: 'DELETE_ACCOUNT_FAIL',

  MAKE_STUDENT_CARD_DEFAULT_START: 'MAKE_STUDENT_CARD_DEFAULT_START',
  MAKE_STUDENT_CARD_DEFAULT_SUCCESS: 'MAKE_STUDENT_CARD_DEFAULT_SUCCESS',
  MAKE_STUDENT_CARD_DEFAULT_FAIL: 'MAKE_STUDENT_CARD_DEFAULT_FAIL',

  FETCH_STUDENT_CARDS_START: 'FETCH_STUDENT_CARDS_START',
  FETCH_STUDENT_CARDS_SUCCESS: 'FETCH_STUDENT_CARDS_SUCCESS',
  FETCH_STUDENT_CARDS_FAIL: 'FETCH_STUDENT_CARDS_FAIL',

  ADD_STUDENT_CARD_START: 'ADD_STUDENT_CARD_START',
  ADD_STUDENT_CARD_SUCCESS: 'ADD_STUDENT_CARD_SUCCESS',
  ADD_STUDENT_CARD_FAIL: 'ADD_STUDENT_CARD_FAIL',

  EDIT_PASSWORD_START: 'EDIT_PASSWORD_START',
  EDIT_PASSWORD_SUCCESS: 'EDIT_PASSWORD_SUCCESS',
  EDIT_PASSWORD_FAIL: 'EDIT_PASSWORD_FAIL',

  BROWSE_PENDING_STUDENT_CARDS_START: 'BROWSE_PENDING_STUDENT_CARDS_START',
  BROWSE_PENDING_STUDENT_CARDS_SUCCESS: 'BROWSE_PENDING_STUDENT_CARDS_SUCCESS',
  BROWSE_PENDING_STUDENT_CARDS_FAIL: 'BROWSE_PENDING_STUDENT_CARDS_FAIL',

  RESEND_EMAIL_VERIFICATION_START: 'RESEND_EMAIL_VERIFICATION_START',
  RESEND_EMAIL_VERIFICATION_SUCCESS: 'RESEND_EMAIL_VERIFICATION_SUCCESS',
  RESEND_EMAIL_VERIFICATION_FAIL: 'RESEND_EMAIL_VERIFICATION_FAIL',

  DELETE_PENDING_STUDENT_CARD_START: 'DELETE_PENDING_STUDENT_CARD_START',
  DELETE_PENDING_STUDENT_CARD_SUCCESS: 'DELETE_PENDING_STUDENT_CARD_SUCCESS',
  DELETE_PENDING_STUDENT_CARD_FAIL: 'DELETE_PENDING_STUDENT_CARD_FAIL',

  ADD_ACCOUNT_START: 'ADD_ACCOUNT_START',
  ADD_ACCOUNT_SUCCESS: 'ADD_ACCOUNT_SUCCESS',
  ADD_ACCOUNT_FAIL: 'ADD_ACCOUNT_FAIL',

  IMPORT_ACCOUNT_START: 'IMPORT_ACCOUNT_START',
  IMPORT_ACCOUNT_SUCCESS: 'IMPORT_ACCOUNT_SUCCESS',
  IMPORT_ACCOUNT_FAIL: 'IMPORT_ACCOUNT_FAIL',

  DOWNLOAD_ACCOUNT_FILE_START: 'DOWNLOAD_ACCOUNT_FILE_START',
  DOWNLOAD_ACCOUNT_FILE_SUCCESS: 'DOWNLOAD_ACCOUNT_FILE_SUCCESS',
  DOWNLOAD_ACCOUNT_FILE_FAIL: 'DOWNLOAD_ACCOUNT_FILE_FAIL',
};

export const systemConstants = {
  // Access log
  FETCH_ACCESS_LOG_START: 'FETCH_ACCESS_LOG_START',
  FETCH_ACCESS_LOG_SUCCESS: 'FETCH_ACCESS_LOG_SUCCESS',
  FETCH_ACCESS_LOG_FAIL: 'FETCH_ACCESS_LOG_FAIL',

  // Announcement
  FETCH_ANNOUNCEMENT_START: 'FETCH_ANNOUNCEMENT_START',
  FETCH_ANNOUNCEMENT_SUCCESS: 'FETCH_ANNOUNCEMENT_SUCCESS',
  FETCH_ANNOUNCEMENT_FAIL: 'FETCH_ANNOUNCEMENT_FAIL',

  ADD_ANNOUNCEMENT_START: 'ADD_ANNOUNCEMENT_START',
  ADD_ANNOUNCEMENT_SUCCESS: 'ADD_ANNOUNCEMENT_SUCCESS',
  ADD_ANNOUNCEMENT_FAIL: 'ADD_ANNOUNCEMENT_FAIL',

  EDIT_ANNOUNCEMENT_START: 'EDIT_ANNOUNCEMENT_START',
  EDIT_ANNOUNCEMENT_SUCCESS: 'EDIT_ANNOUNCEMENT_SUCCESS',
  EDIT_ANNOUNCEMENT_FAIL: 'EDIT_ANNOUNCEMENT_FAIL',

  DELETE_ANNOUNCEMENT_START: 'DELETE_ANNOUNCEMENT_START',
  DELETE_ANNOUNCEMENT_SUCCESS: 'DELETE_ANNOUNCEMENT_SUCCESS',
  DELETE_ANNOUNCEMENT_FAIL: 'DELETE_ANNOUNCEMENT_FAIL',

  // Submission language
  FETCH_SUBMIT_LANGUAGE_START: 'FETCH_SUBMIT_LANGUAGE_START',
  FETCH_SUBMIT_LANGUAGE_SUCCESS: 'FETCH_SUBMIT_LANGUAGE_SUCCESS',
  FETCH_SUBMIT_LANGUAGE_FAIL: 'FETCH_SUBMIT_LANGUAGE_FAIL',

  EDIT_SUBMIT_LANGUAGE_START: 'EDIT_SUBMIT_LANGUAGE_START',
  EDIT_SUBMIT_LANGUAGE_SUCCESS: 'EDIT_SUBMIT_LANGUAGE_SUCCESS',
  EDIT_SUBMIT_LANGUAGE_FAIL: 'EDIT_SUBMIT_LANGUAGE_FAIL',
};

export const courseConstants = {
  FETCH_COURSES_START: 'FETCH_COURSES_START',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAIL: 'FETCH_COURSES_FAIL',

  ADD_COURSE_START: 'ADD_COURSE_START',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAIL: 'ADD_COURSE_FAIL',

  RENAME_COURSE_START: 'RENAME_COURSE_START',
  RENAME_COURSE_SUCCESS: 'RENAME_COURSE_SUCCESS',
  RENAME_COURSE_FAIL: 'RENAME_COURSE_FAIL',

  DELETE_COURSE_START: 'DELETE_COURSE_START',
  DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
  DELETE_COURSE_FAIL: 'DELETE_COURSE_FAIL',

  FETCH_CLASSES_START: 'FETCH_CLASSES_START',
  FETCH_CLASSES_SUCCESS: 'FETCH_CLASSES_SUCCESS',
  FETCH_CLASSES_FAIL: 'FETCH_CLASSES_FAIL',

  ADD_CLASS_START: 'ADD_CLASS_START',
  ADD_CLASS_SUCCESS: 'ADD_CLASS_SUCCESS',
  ADD_CLASS_FAIL: 'ADD_CLASS_FAIL',

  RENAME_CLASS_START: 'RENAME_CLASS_START',
  RENAME_CLASS_SUCCESS: 'RENAME_CLASS_SUCCESS',
  RENAME_CLASS_FAIL: 'RENAME_CLASS_FAIL',

  DELETE_CLASS_START: 'DELETE_CLASS_START',
  DELETE_CLASS_SUCCESS: 'DELETE_CLASS_SUCCESS',
  DELETE_CLASS_FAIL: 'DELETE_CLASS_FAIL',

  FETCH_MEMBERS_START: 'FETCH_MEMBERS_START',
  FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS',
  FETCH_MEMBERS_FAIL: 'FETCH_MEMBERS_FAIL',

  EDIT_MEMBERS_START: 'EDIT_MEMBERS_START',
  EDIT_MEMBERS_SUCCESS: 'EDIT_MEMBERS_SUCCESS',
  EDIT_MEMBERS_FAIL: 'EDIT_MEMBERS_FAIL',
};
