// eslint-disable-next-line import/prefer-default-export
export const accountConstants = {
  FETCH_INSTITUTES_REQUEST: 'FETCH_INSTITUTES_REQUEST',
  FETCH_INSTITUTES_SUCCESS: 'FETCH_INSTITUTES_SUCCESS',
  FETCH_INSTITUTES_FAIL: 'FETCH_INSTITUTES_FAIL',

  FETCH_INSTITUTE_REQUEST: 'FETCH_INSTITUTE_REQUEST',
  FETCH_INSTITUTE_SUCCESS: 'FETCH_INSTITUTE_SUCCESS',
  FETCH_INSTITUTE_FAIL: 'FETCH_INSTITUTE_FAIL',

  ADD_INSTITUTE_REQUEST: 'ADD_INSTITUTE_REQUEST',
  ADD_INSTITUTE_SUCCESS: 'ADD_INSTITUTE_SUCCESS',
  ADD_INSTITUTE_FAIL: 'ADD_INSTITUTE_FAIL',

  EDIT_INSTITUTE_REQUEST: 'RENAME_INSTITUTE_REQUEST',
  EDIT_INSTITUTE_SUCCESS: 'RENAME_INSTITUTE_SUCCESS',
  EDIT_INSTITUTE_FAIL: 'RENAME_INSTITUTE_FAIL',

  FETCH_ACCOUNT_REQUEST: 'FETCH_ACCOUNT_REQUEST',
  FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
  FETCH_ACCOUNT_FAIL: 'FETCH_ACCOUNT_FAIL',

  FETCH_ACCOUNTS_REQUEST: 'FETCH_ACCOUNTS_REQUEST',
  FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
  FETCH_ACCOUNTS_FAIL: 'FETCH_ACCOUNTS_FAIL',

  EDIT_ACCOUNT_REQUEST: 'EDIT_ACCOUNT_REQUEST',
  EDIT_ACCOUNT_SUCCESS: 'EDIT_ACCOUNT_SUCCESS',
  EDIT_ACCOUNT_FAIL: 'EDIT_ACCOUNT_FAIL',

  DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAIL: 'DELETE_ACCOUNT_FAIL',

  MAKE_STUDENT_CARD_DEFAULT_REQUEST: 'MAKE_STUDENT_CARD_DEFAULT_REQUEST',
  MAKE_STUDENT_CARD_DEFAULT_SUCCESS: 'MAKE_STUDENT_CARD_DEFAULT_SUCCESS',
  MAKE_STUDENT_CARD_DEFAULT_FAIL: 'MAKE_STUDENT_CARD_DEFAULT_FAIL',

  FETCH_STUDENT_CARD_REQUEST: 'FETCH_STUDENT_CARD_REQUEST',
  FETCH_STUDENT_CARD_SUCCESS: 'FETCH_STUDENT_CARD_SUCCESS',
  FETCH_STUDENT_CARD_FAIL: 'FETCH_STUDENT_CARD_FAIL',

  ADD_STUDENT_CARD_REQUEST: 'ADD_STUDENT_CARD_REQUEST',
  ADD_STUDENT_CARD_SUCCESS: 'ADD_STUDENT_CARD_SUCCESS',
  ADD_STUDENT_CARD_FAIL: 'ADD_STUDENT_CARD_FAIL',

  EDIT_PASSWORD_REQUEST: 'EDIT_PASSWORD_REQUEST',
  EDIT_PASSWORD_SUCCESS: 'EDIT_PASSWORD_SUCCESS',
  EDIT_PASSWORD_FAIL: 'EDIT_PASSWORD_FAIL',
};

export const systemConstants = {
  // Access log
  FETCH_ACCESS_LOG_START: 'FETCH_ACCESS_LOG_START',
  FETCH_ACCESS_LOG_SUCCESS: 'FETCH_ACCESS_LOG_SUCCESS',
  FETCH_ACCESS_LOG_FAIL: 'FETCH_ACCESS_LOG_FAIL',

  // Announcement
  FETCH_ANNOUNCEMENT_START: 'FETCH_ANNOUNCEMENT_START',
  FETCH_ANNOUNCEMENT_SUCCESS: 'FETCH_ANNOUNCEMENT_SUCCESS',
  FETCH_ANNOUNCEMENT_FAIL: 'FETCH_ANNOUNCEMENT_FAIL',

  ADD_ANNOUNCEMENT_START: 'ADD_ANNOUNCEMENT_START',
  ADD_ANNOUNCEMENT_SUCCESS: 'ADD_ANNOUNCEMENT_SUCCESS',
  ADD_ANNOUNCEMENT_FAIL: 'ADD_ANNOUNCEMENT_FAIL',

  EDIT_ANNOUNCEMENT_START: 'EDIT_ANNOUNCEMENT_START',
  EDIT_ANNOUNCEMENT_SUCCESS: 'EDIT_ANNOUNCEMENT_SUCCESS',
  EDIT_ANNOUNCEMENT_FAIL: 'EDIT_ANNOUNCEMENT_FAIL',

  DELETE_ANNOUNCEMENT_START: 'DELETE_ANNOUNCEMENT_START',
  DELETE_ANNOUNCEMENT_SUCCESS: 'DELETE_ANNOUNCEMENT_SUCCESS',
  DELETE_ANNOUNCEMENT_FAIL: 'DELETE_ANNOUNCEMENT_FAIL',

  // Submission language
  FETCH_SUBMIT_LANGUAGE_START: 'FETCH_SUBMIT_LANGUAGE_START',
  FETCH_SUBMIT_LANGUAGE_SUCCESS: 'FETCH_SUBMIT_LANGUAGE_SUCCESS',
  FETCH_SUBMIT_LANGUAGE_FAIL: 'FETCH_SUBMIT_LANGUAGE_FAIL',

  EDIT_SUBMIT_LANGUAGE_START: 'EDIT_SUBMIT_LANGUAGE_START',
  EDIT_SUBMIT_LANGUAGE_SUCCESS: 'EDIT_SUBMIT_LANGUAGE_SUCCESS',
  EDIT_SUBMIT_LANGUAGE_FAIL: 'EDIT_SUBMIT_LANGUAGE_FAIL',
};
